//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_personne_arpilabe
{
    using System;
    using System.Collections.Generic;
    
    public partial class personne
    {
        public int id { get; set; }
        public string prenom { get; set; }
        public string nom { get; set; }
        public string mail { get; set; }
        public string telephone { get; set; }
        public string note { get; set; }
        public string departement { get; set; }
        public string dateDeNaissance { get; set; }
    }
}
